// <auto-generated />
using AirlineReservationSystem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AirlineReservationSystem.Data.Migrations
{
    [DbContext(typeof(AirplaneReservationSystemContext))]
    [Migration("20260218130938_InitialCreateV2")]
    partial class InitialCreateV2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("AirlineReservationSystem.Models.Airplane", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Airplanes");
                });

            modelBuilder.Entity("AirlineReservationSystem.Models.Customer", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("AirlineReservationSystem.Models.Flight", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ArrivalAirport")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DepartureAirport")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlaneID")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("PlaneID");

                    b.ToTable("Flights");
                });

            modelBuilder.Entity("AirlineReservationSystem.Reservation", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CustomerID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FlightID")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("CustomerID");

                    b.HasIndex("FlightID");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("AirlineReservationSystem.Seat", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FlightID")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ReservationID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SeatClass")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("FlightID");

                    b.HasIndex("ReservationID");

                    b.ToTable("Seat");
                });

            modelBuilder.Entity("AirlineReservationSystem.Models.Flight", b =>
                {
                    b.HasOne("AirlineReservationSystem.Models.Airplane", "Plane")
                        .WithMany()
                        .HasForeignKey("PlaneID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plane");
                });

            modelBuilder.Entity("AirlineReservationSystem.Reservation", b =>
                {
                    b.HasOne("AirlineReservationSystem.Models.Customer", "Customer")
                        .WithMany("Reservations")
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AirlineReservationSystem.Models.Flight", "Flight")
                        .WithMany()
                        .HasForeignKey("FlightID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Flight");
                });

            modelBuilder.Entity("AirlineReservationSystem.Seat", b =>
                {
                    b.HasOne("AirlineReservationSystem.Models.Flight", null)
                        .WithMany("Seats")
                        .HasForeignKey("FlightID");

                    b.HasOne("AirlineReservationSystem.Reservation", null)
                        .WithMany("Seats")
                        .HasForeignKey("ReservationID");
                });

            modelBuilder.Entity("AirlineReservationSystem.Models.Customer", b =>
                {
                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("AirlineReservationSystem.Models.Flight", b =>
                {
                    b.Navigation("Seats");
                });

            modelBuilder.Entity("AirlineReservationSystem.Reservation", b =>
                {
                    b.Navigation("Seats");
                });
#pragma warning restore 612, 618
        }
    }
}
