// <auto-generated />
using AirlineReservationSystem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AirlineReservationSystem.Migrations
{
    [DbContext(typeof(AirplaneReservationSystemContext))]
    [Migration("20260218171653_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("AirlineReservationSystem.Models.Airplane", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Airplanes");
                });

            modelBuilder.Entity("AirlineReservationSystem.Models.Customer", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("AirlineReservationSystem.Models.Flight", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AirplaneID")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AirplaneID1")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ArrivalAirport")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DepartureAirport")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("AirplaneID");

                    b.HasIndex("AirplaneID1");

                    b.ToTable("Flights");
                });

            modelBuilder.Entity("AirlineReservationSystem.Models.Reservation", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CustomerID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FlightID")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FlightID1")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("CustomerID");

                    b.HasIndex("FlightID");

                    b.HasIndex("FlightID1");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("AirlineReservationSystem.Seat", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AirplaneID")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FlightID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ReservationID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SeatClass")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SeatColumn")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SeatNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SeatRow")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("AirplaneID");

                    b.HasIndex("FlightID");

                    b.HasIndex("ReservationID");

                    b.ToTable("Seat");
                });

            modelBuilder.Entity("AirlineReservationSystem.Models.Flight", b =>
                {
                    b.HasOne("AirlineReservationSystem.Models.Airplane", "Airplane")
                        .WithMany()
                        .HasForeignKey("AirplaneID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AirlineReservationSystem.Models.Airplane", null)
                        .WithMany("Flights")
                        .HasForeignKey("AirplaneID1");

                    b.Navigation("Airplane");
                });

            modelBuilder.Entity("AirlineReservationSystem.Models.Reservation", b =>
                {
                    b.HasOne("AirlineReservationSystem.Models.Customer", "Customer")
                        .WithMany("Reservations")
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AirlineReservationSystem.Models.Flight", "Flight")
                        .WithMany()
                        .HasForeignKey("FlightID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AirlineReservationSystem.Models.Flight", null)
                        .WithMany("Reservations")
                        .HasForeignKey("FlightID1");

                    b.Navigation("Customer");

                    b.Navigation("Flight");
                });

            modelBuilder.Entity("AirlineReservationSystem.Seat", b =>
                {
                    b.HasOne("AirlineReservationSystem.Models.Airplane", null)
                        .WithMany("AirplaneSeats")
                        .HasForeignKey("AirplaneID");

                    b.HasOne("AirlineReservationSystem.Models.Flight", null)
                        .WithMany("FlightSeats")
                        .HasForeignKey("FlightID");

                    b.HasOne("AirlineReservationSystem.Models.Reservation", "Reservation")
                        .WithMany("Seats")
                        .HasForeignKey("ReservationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reservation");
                });

            modelBuilder.Entity("AirlineReservationSystem.Models.Airplane", b =>
                {
                    b.Navigation("AirplaneSeats");

                    b.Navigation("Flights");
                });

            modelBuilder.Entity("AirlineReservationSystem.Models.Customer", b =>
                {
                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("AirlineReservationSystem.Models.Flight", b =>
                {
                    b.Navigation("FlightSeats");

                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("AirlineReservationSystem.Models.Reservation", b =>
                {
                    b.Navigation("Seats");
                });
#pragma warning restore 612, 618
        }
    }
}
