// <auto-generated />
using System;
using AirlineReservationSystem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AirlineReservationSystem.Migrations
{
    [DbContext(typeof(AirplaneReservationSystemContext))]
    partial class AirplaneReservationSystemContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("AirlineReservationSystem.Models.Airplane", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Airplanes");
                });

            modelBuilder.Entity("AirlineReservationSystem.Models.Customer", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("EmailAdress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("AirlineReservationSystem.Models.Flight", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AirplaneID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ArrivalAirport")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("BusinessPrice")
                        .HasColumnType("TEXT");

                    b.Property<bool>("CurrentStatus")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("DateOfFlight")
                        .HasColumnType("TEXT");

                    b.Property<int>("DepartureAirport")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("EconomyPrice")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("AirplaneID");

                    b.ToTable("Flights");
                });

            modelBuilder.Entity("AirlineReservationSystem.Models.FlightSeat", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FlightID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SeatID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("FlightID");

                    b.HasIndex("SeatID");

                    b.ToTable("FlightSeats");
                });

            modelBuilder.Entity("AirlineReservationSystem.Models.Reservation", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CustomerID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FlightID")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("CustomerID");

                    b.HasIndex("FlightID");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("AirlineReservationSystem.Models.Seat", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AirplaneID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SeatClass")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SeatColumn")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SeatNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SeatRow")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("AirplaneID");

                    b.ToTable("Seats");
                });

            modelBuilder.Entity("AirlineReservationSystem.ReservationSeat", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FlightSeatID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ReservationID")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("FlightSeatID");

                    b.HasIndex("ReservationID");

                    b.ToTable("ReservationSeats");
                });

            modelBuilder.Entity("AirlineReservationSystem.Models.Flight", b =>
                {
                    b.HasOne("AirlineReservationSystem.Models.Airplane", "Airplane")
                        .WithMany("Flights")
                        .HasForeignKey("AirplaneID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Airplane");
                });

            modelBuilder.Entity("AirlineReservationSystem.Models.FlightSeat", b =>
                {
                    b.HasOne("AirlineReservationSystem.Models.Flight", "Flight")
                        .WithMany("FlightSeats")
                        .HasForeignKey("FlightID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AirlineReservationSystem.Models.Seat", "Seat")
                        .WithMany("FlightSeats")
                        .HasForeignKey("SeatID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Flight");

                    b.Navigation("Seat");
                });

            modelBuilder.Entity("AirlineReservationSystem.Models.Reservation", b =>
                {
                    b.HasOne("AirlineReservationSystem.Models.Customer", "Customer")
                        .WithMany("Reservations")
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AirlineReservationSystem.Models.Flight", "Flight")
                        .WithMany("Reservations")
                        .HasForeignKey("FlightID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Flight");
                });

            modelBuilder.Entity("AirlineReservationSystem.Models.Seat", b =>
                {
                    b.HasOne("AirlineReservationSystem.Models.Airplane", "Airplane")
                        .WithMany("Seats")
                        .HasForeignKey("AirplaneID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Airplane");
                });

            modelBuilder.Entity("AirlineReservationSystem.ReservationSeat", b =>
                {
                    b.HasOne("AirlineReservationSystem.Models.FlightSeat", "FlightSeat")
                        .WithMany()
                        .HasForeignKey("FlightSeatID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AirlineReservationSystem.Models.Reservation", "Reservation")
                        .WithMany("ReservationSeats")
                        .HasForeignKey("ReservationID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FlightSeat");

                    b.Navigation("Reservation");
                });

            modelBuilder.Entity("AirlineReservationSystem.Models.Airplane", b =>
                {
                    b.Navigation("Flights");

                    b.Navigation("Seats");
                });

            modelBuilder.Entity("AirlineReservationSystem.Models.Customer", b =>
                {
                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("AirlineReservationSystem.Models.Flight", b =>
                {
                    b.Navigation("FlightSeats");

                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("AirlineReservationSystem.Models.Reservation", b =>
                {
                    b.Navigation("ReservationSeats");
                });

            modelBuilder.Entity("AirlineReservationSystem.Models.Seat", b =>
                {
                    b.Navigation("FlightSeats");
                });
#pragma warning restore 612, 618
        }
    }
}
